# Generated by Django 4.1.3 on 2022-12-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vol',
            name='heure',
            field=models.TimeField(),
        ),
    ]
