# Generated by Django 4.1.3 on 2022-12-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReserv', '0002_alter_vol_date_alter_vol_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='logo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
