# Generated by Django 4.1.3 on 2022-12-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReserv', '0004_alter_compagnie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='logo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
