# Generated by Django 4.1.3 on 2022-12-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReserv', '0005_alter_compagnie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='compagnie',
            field=models.ManyToManyField(related_name='vols', to='appReserv.compagnie'),
        ),
    ]
